namespace Ecng.Data.Sql;

/// <summary>
/// https://stackoverflow.com/questions/7731905/how-to-convert-an-expression-tree-to-a-partial-sql-query
/// </summary>
class ExpressionQueryTranslator(Schema meta) : ExpressionVisitor
{
	public const string CancellationTokenKey = "cancellationToken";

	public IDictionary<string, (Type, object)> Parameters => Context.Parameters;

	private readonly Schema _meta = meta ?? throw new ArgumentNullException(nameof(meta));

	public Context Context { get; internal set; }

	private Query Curr
	{
		get => Context.Curr;
		set => Context.Curr = value;
	}

	public Queue<Action<bool, Query>> WrapColumn => Context.WrapColumn;

	public Query GenerateSql(Expression expression)
	{
		Context = new() { TableAlias = Extensions.DefaultAlias };

		Visit(expression);

		var query = Context.Build(_meta);

		if (Context.Count)
		{
			if (expression is MethodCallExpression methodExp && methodExp.Arguments.Count > 1 && methodExp.Arguments[1] is ConstantExpression constExp)
			{
				Context.Parameters.Add(CancellationTokenKey, (constExp.Type, constExp.Value));
			}
		}

		return query;
	}

	protected override Expression VisitMethodCall(MethodCallExpression m)
	{
		switch (m.Method.Name)
		{
			case nameof(Queryable.Where):
			{
				var c = Curr = new();

				Visit(m.Arguments[0]);

				Curr = c;
				var lambda = (LambdaExpression)m.Arguments[1].StripQuotes();

				var isBoolEqual = lambda.Body is MemberExpression me && me.Type == typeof(bool);

				if (isBoolEqual)
					Curr.OpenBracket();

				var isWhere = Context.IsWhere;
				Context.IsWhere = true;
				Visit(lambda.Body);
				Context.IsWhere = isWhere;

				if (isBoolEqual)
				{
					Curr.IsTrue();
					Curr.CloseBracket();
				}

				if (lambda.Parameters.Count > 0 && lambda.Parameters[0].Type.GetGenericType(typeof(IGrouping<,>)) is not null)
					Context.HavingParts.Add(Curr);
				else
					Context.WhereParts.Add(Curr);
				
				return m;
			}

			case nameof(Queryable.Take):
			{
				Context.Take = m.Arguments[1].GetConstant<long>();
				return Visit(m.Arguments[0]);
			}

			case nameof(QueryableExtensions.FirstOrDefaultAsync):
			{
				Context.Take = 1;

				var constExp = (ConstantExpression)m.Arguments[1];
				Context.Parameters.Add(CancellationTokenKey, (constExp.Type, constExp.Value));

				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.Skip):
			case nameof(QueryableExtensions.SkipLong):
			{
				Context.Skip = m.Arguments[1].GetConstant<long>();
				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.OrderBy):
			{
				ParseOrderByExpression(m, true);
				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.OrderByDescending):
			{
				ParseOrderByExpression(m, false);
				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.ThenBy):
			{
				ParseOrderByExpression(m, true);
				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.ThenByDescending):
			{
				ParseOrderByExpression(m, false);
				return Visit(m.Arguments[0]);
			}

			case nameof(QueryableExtensions.CountAsync):
			{
				Context.Count = true;
				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.Select):
			{
				var body = m.Arguments[1].GetOperand().Body;

				if (body is MemberInitExpression)
				{
					Visit(body);
				}
				else if (body is NewExpression)
				{
					var isSelect = Context.IsSelect;
					Context.IsSelect = true;
					Visit(body);
					Context.IsSelect = isSelect;
				}
				else if (body is MemberExpression me)
				{
					// Selecting entity from anonymous join type (transparent identifier)?
					var memberType = me.Member.GetMemberType();
					if (!memberType.IsSerializablePrimitive() && SchemaRegistry.TryGet(memberType, out _))
					{
						var isAnonymousAccess =
							(me.Expression is ParameterExpression anonPe && anonPe.Type.IsAutoGenerated()) ||
							(me.Expression is MemberExpression anonMe &&
								(anonMe.Type.IsAutoGenerated() || anonMe.Member.DeclaringType.IsAutoGenerated()));

						if (isAnonymousAccess)
						{
							Context.SelectAlias = me.Member.Name;
							Context.SelectColumns.Add(new());
							return Visit(m.Arguments[0]);
						}
					}

					var curr = Curr;

					var selCols = new ContextSelectColumns();
					Context.SelectColumns.Add(selCols);

					var q = new Query { WrapColumn = WrapColumn };
					Curr = q;

					if (
						me.Expression is MemberExpression me2 &&
						me2.Member.Name == nameof(IGrouping<int, int>.Key) &&
						me2.Member.ReflectedType.GetGenericType(typeof(IGrouping<,>)) is not null)
					{
						var me3 = (MemberExpression)((LambdaExpression)((MethodCallExpression)((MethodCallExpression)m.Arguments[0]).Arguments[0]).Arguments[1].StripQuotes()).Body;
						selCols.Add(me3.Member, (q, me));
						Visit(me3);
					}
					else
					{
						selCols.Add(me.Member, (q, me));
						Visit(body);
					}

					Curr = curr;
				}
				else if (body is UnaryExpression ue && ue.Method is not null)
				{
					if (ue.Method.TryGetVisitor(out var visitor))
					{
						var curr = Curr;

						var selCols = new ContextSelectColumns();
						Context.SelectColumns.Add(selCols);

						var me2 = (MemberExpression)ue.Operand;

						var q = new Query { WrapColumn = WrapColumn };
						selCols.Add(me2.Member, (q, me2));

						Curr = q;
						visitor.Visit(this, me2);

						Curr = curr;
					}
					else
						throw new NotSupportedException();
				}
				else
					throw new NotSupportedException();

				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.SelectMany):
			{
				var resultSelector = m.Arguments[2].GetOperand();

				var leftJoinAlias = Context.LeftJoinAlias;
				Context.LeftJoinAlias = resultSelector.Parameters[1].Name;
				var retVal = Visit(m.Arguments[0]);
				Context.LeftJoinAlias = leftJoinAlias;

				if (resultSelector.Body is MemberInitExpression)
				{
					// final projection folded into SelectMany result selector
					Visit(resultSelector.Body);
				}

				return retVal;
			}

			case nameof(Queryable.Join):
			{
				var joinPart = new Query();

				Curr = joinPart;

				if (m.Arguments[0].NodeType == ExpressionType.Call)
				{
					Visit(m.Arguments[0]);
					Curr = joinPart;
				}

				static (Schema meta, string tableAlias, string column) GetInfo(Expression exp)
				{
					var operand = exp.GetOperand();

					if (operand.Body is ParameterExpression pe1)
						return (default(Schema), pe1.Name, "Id");

					var member = (MemberExpression)(operand.Body is UnaryExpression ue ? ue.Operand : operand.Body);

					var tableAlias = member.Expression is ParameterExpression pe
						? pe.Name
						: member.GetMemberName();

					var memberName = member.Member.Name;

					var owner = operand.Parameters[0].Type;

					if (memberName == Extensions.IdColName && member.Expression is MemberExpression innerMember)
					{
						memberName = innerMember.Member.Name;

						if (!innerMember.Member.DeclaringType.IsAbstract)
							owner = innerMember.Member.DeclaringType;
					}

					if (owner.IsAutoGenerated())
					{
						if (operand.Body is MemberExpression me && me.Expression is MemberExpression me2)
						{
							owner = me2.Type;
							memberName = me.Member.Name;
						}
					}

					var meta = SchemaRegistry.Get(owner);
					return (meta, tableAlias, memberName);
				}

				Curr.InnerJoin();

				var (meta1, alias1, col1) = GetInfo(m.Arguments[2]);
				var (meta2, alias2, col2) = GetInfo(m.Arguments[3]);

				var prevAlias = Context.CurrJoinAlias;

				try
				{
					var origAlias = alias2;

					while (Context.JoinParts.Any(t => t.tableAlias.EqualsIgnoreCase(alias2)))
					{
						alias2 += "1";
					}

					if (origAlias != alias2)
						Context.CurrJoinAlias = (origAlias, alias2);

					if (m.Arguments[1] is MethodCallExpression mce)
					{
						var attr = mce.Method.GetAttribute<SqlExternalAttribute>();

						if (attr is not null)
							this.RenderFuncCall(Curr, mce, attr);
						else
						{
							if (mce.Method.TryGetVisitor(out var visitor))
							{
								Curr.OpenBracket();
								visitor.Visit(this, mce);
								Curr.CloseBracket();
							}
							else
								throw new NotSupportedException(mce.Method.To<string>());
						}

						Curr.As().Column(alias2);
					}
					else
					{
						Curr.Table(meta2.Name, alias2);
					}

					Curr.On().Column(alias2, col2).Equal().Column(GetAlias(alias1), col1).NewLine();

					Context.JoinParts.Add((alias2, joinPart));

					var resultSelector = m.Arguments[4].GetOperand();
					if (resultSelector.Body is ParameterExpression resultParam &&
						resultParam == resultSelector.Parameters[1])
					{
						// select inner entity → SELECT [alias2].*
						Context.SelectAlias = alias2;
					}
					else if (resultSelector.Body is MemberInitExpression)
					{
						// final projection folded into Join result selector
						// (e.g., select new VError { Text = ec.Value, ... })
						Visit(resultSelector.Body);
					}

					return m;
				}
				finally
				{
					Context.CurrJoinAlias = prevAlias;
				}
			}

			case nameof(Queryable.Distinct):
			{
				Context.Distinct = true;
				return Visit(m.Arguments[0]);
			}

			case nameof(Queryable.GroupJoin):
			{
				var joinPart = new Query();

				Curr = joinPart;

				if (m.Arguments[0].NodeType == ExpressionType.Call)
				{
					Visit(m.Arguments[0]);
					Curr = joinPart;
				}

				static (Schema meta, string tableAlias, (bool isColumn, object value)[] columns) GetInfo(Expression exp)
				{
					Schema meta = default;
					string tableAlias = default;
					var cols = new List<(bool isColumn, object value)>();

					static object BoolAsInt(object value)
					{
						if (value is bool b)
							value = b ? 1 : 0;

						return value;
					}

					var operand = exp.GetOperand();

					if (operand.Body is NewExpression newExp)
					{
						foreach (var arg in newExp.Arguments)
						{
							var ae = arg.StripQuotes();

							if (ae is MemberExpression member)
							{
								tableAlias = member.Expression is ParameterExpression pe
									? pe.Name
									: member.GetMemberName();

								var memberName = member.Member.Name;
								var owner = operand.Parameters[0].Type;

								if (memberName == Extensions.IdColName && member.Expression is MemberExpression innerMember)
								{
									if (innerMember.Member.DeclaringType.IsAutoGenerated())
									{
										owner = innerMember.Member.GetMemberType();
									}
									else
									{
										memberName = innerMember.Member.Name;

										if (!innerMember.Member.DeclaringType.IsAbstract)
											owner = innerMember.Member.DeclaringType;
									}
								}

								meta = SchemaRegistry.Get(owner);
								cols.Add((true, memberName));
							}
							else if (ae is UnaryExpression u)
							{
								cols.Add((false, BoolAsInt(u.Operand.GetConstant<object>())));
							}
							else
								cols.Add((false, BoolAsInt(ae.GetConstant<object>())));
						}
					}
					else
					{
						var member = (MemberExpression)operand.Body;

						tableAlias = member.Expression is ParameterExpression pe
							? pe.Name
							: member.GetMemberName();

						var memberName = member.Member.Name;
						var owner = operand.Parameters[0].Type;

						if (memberName == Extensions.IdColName && member.Expression is MemberExpression innerMember)
						{
							if (innerMember.Member.DeclaringType.IsAutoGenerated())
							{
								owner = innerMember.Member.GetMemberType();
							}
							else
							{
								memberName = innerMember.Member.Name;

								if (!innerMember.Member.DeclaringType.IsAbstract)
									owner = innerMember.Member.DeclaringType;
							}
						}

						meta = SchemaRegistry.Get(owner);
						cols.Add((true, memberName));
					}

					return (meta, tableAlias, cols.ToArray());
				}

				Curr.LeftJoin();

				var (meta1, alias1, col1) = GetInfo(m.Arguments[2]);
				var (meta2, alias2, col2) = GetInfo(m.Arguments[3]);

				if (col1.Length != col2.Length)
					throw new InvalidOperationException($"col1={col1.Length} <> col2={col2.Length}");

				alias2 = Context.LeftJoinAlias.IsEmpty(alias2);

				if (m.Arguments[1] is MethodCallExpression mce)
				{
					var attr = mce.Method.GetAttribute<SqlExternalAttribute>();

					if (attr is null)
						throw new NotSupportedException();

					this.RenderFuncCall(Curr, mce, attr);
					Curr.As().Column(alias2);
				}
				else
				{
					Curr.Table(meta2.Name, alias2);
				}

				Curr.On();

				for (var i = 0; i < col1.Length; i++)
				{
					if (i > 0)
						Curr.And();

					var isNull = (!col1[i].isColumn || !col2[i].isColumn) && (col1[i].value is null || col2[i].value is null);

					if (col1[i].isColumn)
						Curr.Column(GetAlias(alias1), (string)col1[i].value);
					else
					{
						if (isNull && col1[i].value is null)
						{
							if (col2[i].isColumn)
								Curr.Column(alias2, (string)col2[i].value);
							else
								Curr.Raw(col2[i].value.To<string>());
						}
						else
							Curr.Raw(col1[i].value.To<string>());
					}

					if (isNull)
						Curr.Is().Null();
					else
					{
						Curr.Equal();

						if (col2[i].isColumn)
							Curr.Column(alias2, (string)col2[i].value);
						else
							Curr.Raw(col2[i].value.To<string>());
					}
				}

				Curr.NewLine();

				Context.JoinParts.Add((alias2, joinPart));

				return m;
			}

			case nameof(Queryable.GroupBy):
			{
				Visit(m.Arguments[0]);

				var curr = Curr;
				Curr = Context.GroupByPart;

				Curr.GroupBy();

				var isGroup = Context.IsGroup;

				Context.IsGroup = true;
				var retVal = Visit(m.Arguments[1].StripQuotes());
				Context.IsGroup = isGroup;

				Curr = curr;

				return retVal;
			}

			default:
			{
				if (m.Method.TryGetVisitor(out var visitor))
				{
					visitor.Visit(this, m);
					return m;
				}

				var attr = m.Method.GetAttribute<SqlExternalAttribute>();

				if (attr is null)
					break;

				var needBrackets = false;

				if (Curr is null)
					Curr = Context.FromPart;
				else
					needBrackets = true;

				if (needBrackets)
					Curr.OpenBracket();

				this.RenderFuncCall(Curr, m, attr);

				if (needBrackets)
				{
					if (m.Method.ReturnType == typeof(bool))
						Curr.IsTrue();

					Curr.CloseBracket();
				}

				return m;
			}
		}

		throw new NotSupportedException($"The method '{m.Method.Name}' is not supported");
	}

	protected override Expression VisitConditional(ConditionalExpression node)
	{
		Curr = Context.SwitchPart;

		Curr
			.Case()
			.NewLine();

		Curr.When();
		Visit(node.Test);

		Curr.Then();
		Visit(node.IfTrue);

		Curr.NewLine();

		Curr.Else();
		Visit(node.IfFalse);

		Curr.NewLine().End();

		return node;
	}

	private Expression ProcessInitExpression(Expression maExp)
	{
		if (maExp.NodeType == ExpressionType.Convert)
		{
			maExp = ((UnaryExpression)maExp).Operand;
		}

		var ctx = Context;

		MethodVisitor visitor = default;

		var isSubquery = (maExp is MethodCallExpression ce /*&& ce.Arguments.Count == 1*/ && (!ce.Method.TryGetVisitor(out visitor) || (ce.Arguments.Count > 0 && ce.Arguments[0].NodeType == ExpressionType.Call)) &&
			(
				!(ce.Method.DeclaringType == typeof(Enumerable) && ce.Method.Name == nameof(Enumerable.Count)) ||
				(ce.Arguments.Count > 0 && ce.Arguments[0].NodeType != ExpressionType.Parameter)
			)) || maExp is ConditionalExpression;

		if (isSubquery)
		{
			Curr.OpenBracket();
			Curr.NewLine();

			Context = new() { ParamCountOffset = ctx.Parameters.Count + ctx.ParamCountOffset };

			if (visitor?.GetType().GetGenericType(typeof(CountVisitor<>)) != null)
				Context.Count = true;
		}

		Visit(maExp);

		if (isSubquery)
		{
			Type itemType;

			if (maExp is MethodCallExpression mca)
			{
				var args = mca.Method.GetGenericArguments();

				itemType = args.Length > 0 ? args[0] : typeof(int);

				while (mca.Arguments[0] is MethodCallExpression mca1)
					mca = mca1;

				Context.TableAlias = (mca.Arguments[1] is MemberExpression
					? mca.Arguments[2]
					: mca.Arguments[1])
				.GetOperand().Parameters[0].Name;

				if (itemType.IsSerializablePrimitive())
				{
					itemType = ((MemberExpression)mca.Arguments[0]).Member.GetMemberType().GetGenericArguments()[0];
				}
			}
			else
				itemType = _meta.EntityType;

			var subquery = Context.Build(SchemaRegistry.Get(itemType));

			var subParams = Context.Parameters;

			Context = ctx;
			subquery.CopyTo(Curr);
			Curr.CloseBracket();

			Context.AddParamsFromSubquery(subParams, false);
		}

		return maExp;
	}

	protected override Expression VisitMemberInit(MemberInitExpression i)
	{
		var selectColumns = new ContextSelectColumns();

		var curr = Curr;

		foreach (var b in i.Bindings)
		{
			Curr = new Query { WrapColumn = WrapColumn };

			var ma = (MemberAssignment)b;
			var maExp = ma.Expression;

			if (maExp is MemberExpression me &&
				me.Member is PropertyInfo pi &&
				pi.Name == nameof(IGrouping<int, int>.Key) &&
				pi.ReflectedType.GetGenericType(typeof(IGrouping<,>)) is not null)
			{
				Curr.Column(b.Member.Name);
			}
			else
			{
				if (maExp is MemberInitExpression mi)
				{
					var inner = ((MemberAssignment)mi.Bindings[0]).Expression;
					Visit(inner);

					if (inner is MemberExpression me2)
					{
						if (b.Member != me2.Member && me2.Member.Name == Extensions.IdColName && !me2.Member.DeclaringType.IsAutoGenerated() && me2.Expression is MemberExpression innerMember)
							selectColumns.Map.Add(b.Member, innerMember.Member);
						else
							selectColumns.Map.Add(b.Member, me2.Member);
					}
				}
				else
				{
					maExp = ProcessInitExpression(maExp);

					if (maExp is MemberExpression me2)
					{
						if (b.Member != me2.Member && me2.Member.Name == Extensions.IdColName && me2.Expression is MemberExpression innerMember)
							selectColumns.Map.Add(b.Member, innerMember.Member);
						else
							selectColumns.Map.Add(b.Member, me2.Member);

						if (me2.Member != ma.Member && !me2.Member.TryGetVisitor(out _))
							Context.Members[(i.Type, ma.Member)] = me2;
					}
				}
			}

			selectColumns.Add(b.Member, (Curr, maExp));
		}

		Curr = curr;

		Context.SelectColumns.Add(selectColumns);

		return i;
	}

	protected override Expression VisitNew(NewExpression n)
	{
		var curr = Context.Curr;

		var isGroup = Context.IsGroup;
		var isSelect = Context.IsSelect;

		if (!isGroup && !isSelect)
			return n;

		var selCols = new ContextSelectColumns();

		var argCount = n.Arguments.Count;

		for (var i = 0; i < argCount; i++)
		{
			MemberInfo member;

			if (n.Members is not null)
			{
				member = n.Members[i];
			}
			else
			{
				// Positional constructor (e.g. record Dto(long Id, string Name)) — the
				// compiler does not populate NewExpression.Members. Derive the member
				// from the ctor parameter name by matching a property on the result type.
				var paramName = n.Constructor.GetParameters()[i].Name;
				member = n.Type.GetProperty(paramName, BindingFlags.Public | BindingFlags.Instance | BindingFlags.IgnoreCase)
					?? throw new NotSupportedException($"Cannot map ctor parameter '{paramName}' to a property of {n.Type}.");
			}

			if (!isSelect && i > 0)
				Curr.Comma();

			var arg = n.Arguments[i];

			if (arg is MemberExpression me &&
				me.Member is PropertyInfo pi &&
				pi.Name == nameof(IGrouping<int, int>.Key) &&
				pi.ReflectedType.GetGenericType(typeof(IGrouping<,>)) is not null)
			{
			}
			else
			{
				var ctx = Context;

				if (isGroup)
				{
					Context = new();
					Context.Curr = Context.GroupByPart;
				}
				else if (isSelect)
					Context.Curr = new();

				Visit(n.Arguments[i]);

				if (isGroup)
				{
					selCols.Add(member, (Context.Curr, arg));

					var subParams = Context.Parameters;

					var actions = Context.Curr.Actions.ToArray();

					ctx.Curr.Actions.AddRange(actions);

					Context = ctx;

					Context.AddParamsFromSubquery(subParams);
				}
				else if (isSelect)
				{
					if (arg is MemberExpression me2)
					{
						if (Context.SelectColumns.Count > 0)
						{
							var prev = Context.SelectColumns.Last();
							prev.Map.Add(member, me2.Member);

							selCols.Add(me2.Member, (Context.Curr, arg));
						}
						else
						{
							// Top-level anonymous projection over a table: no previous select
							// layer to attach Map to. Keep the rename map on the current
							// selCols and use the anonymous member as the key so rendering
							// emits the AS alias correctly.
							selCols.Map.Add(member, me2.Member);
							selCols.Add(member, (Context.Curr, arg));
						}
					}

					Context.Curr = curr;
				}
			}
		}

		Context.SelectColumns.Add(selCols);

		return n;
	}

	protected override Expression VisitUnary(UnaryExpression u)
	{
		switch (u.NodeType)
		{
			case ExpressionType.Not:
				if (u.Operand is MemberExpression me && me.Type == typeof(bool))
				{
					Curr.OpenBracket();

					Visit(u.Operand);
					Curr.IsFalse();

					Curr.CloseBracket();
				}
				else
				{
					Curr.Not();
					Curr.OpenBracket();

					Visit(u.Operand);

					Curr.CloseBracket();
				}
				
				break;
			case ExpressionType.Convert:
				if (u.Method is not null)
				{
					if (u.Method.TryGetVisitor(out var visitor))
					{
						visitor.Visit(this, u.Operand);
						break;
					}
					else
						throw new NotSupportedException();
				}
				else
					Visit(u.Operand);
				break;
			case ExpressionType.ArrayLength:
				Curr.DataLength();
				Curr.OpenBracket();
				Visit(u.Operand);
				Curr.CloseBracket();
				break;
			case ExpressionType.Negate:
				Curr.Raw(" -1 * ");
				ProcessInitExpression(u.Operand);
				break;
			case ExpressionType.Quote:
				Visit(u.StripQuotes());
				break;
			default:
				throw new NotSupportedException($"The unary operator '{u.NodeType}' is not supported");
		}

		return u;
	}

	protected override Expression VisitBinary(BinaryExpression b)
	{
		Curr.OpenBracket();

		if (b.NodeType == ExpressionType.Coalesce)
		{
			Curr
				.IsNull()
				.OpenBracket();
		}

		var isLeftBool = b.Left is MemberExpression leftMe && leftMe.Member.GetMemberType() == typeof(bool) && (b.NodeType == ExpressionType.AndAlso || b.NodeType == ExpressionType.OrElse);

		if (isLeftBool)
			Curr.OpenBracket();

		Visit(b.Left);

		switch (b.NodeType)
		{
			case ExpressionType.And:
				if (b.Type == typeof(int))
					Curr.BitwiseAnd();
				else
					Curr.And();
				break;

			case ExpressionType.AndAlso:
				if (isLeftBool)
					Curr.IsTrue().CloseBracket();

				Curr.And();
				break;

			case ExpressionType.Or:
				if (b.Type == typeof(int))
					Curr.BitwiseOr();
				else
					Curr.Or();
				break;

			case ExpressionType.OrElse:
				if (isLeftBool)
					Curr.IsTrue().CloseBracket();

				Curr.Or();
				break;

			case ExpressionType.Equal:
				if (b.Right.IsNullConstant())
				{
					Curr.Is();
				}
				else
				{
					Curr.Equal();
				}
				break;

			case ExpressionType.NotEqual:
				if (b.Right.IsNullConstant())
				{
					Curr.IsNot();
				}
				else
				{
					Curr.NotEqual();
				}
				break;

			case ExpressionType.LessThan:
				Curr.Less();
				break;

			case ExpressionType.LessThanOrEqual:
				Curr.LessOrEqual();
				break;

			case ExpressionType.GreaterThan:
				Curr.More();
				break;

			case ExpressionType.GreaterThanOrEqual:
				Curr.MoreOrEqual();
				break;

			case ExpressionType.Coalesce:
				Curr.Comma();
				break;

			case ExpressionType.Add:
				if (b.Type == typeof(string))
					Curr.Concat();
				else
					Curr.Plus();
				break;

			default:
				throw new NotSupportedException($"The binary operator '{b.NodeType}' is not supported");

		}

		var isRightBool = (b.NodeType == ExpressionType.AndAlso || b.NodeType == ExpressionType.OrElse) && b.Right is MemberExpression rightMe && rightMe.Type == typeof(bool);

		if (isRightBool)
			Curr.OpenBracket();

		Visit(b.Right);

		if (isRightBool)
			Curr.IsTrue().CloseBracket();
		else if (b.NodeType == ExpressionType.Coalesce)
			Curr.CloseBracket();

		Curr.CloseBracket();
		return b;
	}

	protected override Expression VisitConstant(ConstantExpression c)
	{
		var value = c.Value;

		if (value is not IQueryable)
		{
			if (value is null)
			{
				Curr.Null();
			}
			else if (value is bool bVal)
			{
				Curr.AddAction((d, sb) => sb.Append(bVal ? d.TrueLiteral : d.FalseLiteral));
			}
			else if (value is string str)
			{
				Curr.Param(Context.TryAddParam("p", typeof(string), str));
			}
			else
			{
				if (value is Enum)
					value = value.To<long>();

				Curr.Raw(string.Format(System.Globalization.CultureInfo.InvariantCulture, "{0}", value));
			}
		}

		return c;
	}

	private string GetAlias(string alias)
	{
		if (Context.CurrJoinAlias.origAlias == alias)
			return Context.CurrJoinAlias.modifiedAlias;

		// If this alias belongs to a joined table, keep it as-is
		if (Context.JoinParts.Any(j => j.tableAlias.EqualsIgnoreCase(alias)))
			return alias;

		// Otherwise, map to the main table alias.
		// When TableAlias is not yet set (e.g. inside a subquery before Build),
		// return the alias as-is so both inner and outer scope references are preserved.
		return Context.TableAlias.IsEmpty() ? alias : Context.TableAlias;
	}

	protected override Expression VisitMember(MemberExpression m)
	{
		if (m.Expression != null/* && m.Expression.NodeType == ExpressionType.Parameter*/)
		{
			if (Context.Members.TryGetValue((m.Expression.Type, m.Member), out var exp))
			{
				Visit(exp);
				return exp;
			}

			if (m.Expression is ConstantExpression ce)
			{
				var memberValue = m.Member.GetMemberValue(ce.Value);

				// pre-filtered IQueryable (e.g. tasks.Where(x => ...)) has a non-constant Expression
				// that must be visited to capture inner filters and parameters
				if (memberValue is IQueryable q && q.Expression is not ConstantExpression)
					Visit(q.Expression);
				else
					Context.TryAddParam(m.Member, ce.Value);
			}
			else if (m.Expression.NodeType == ExpressionType.MemberAccess)
			{
				if (m.Member.TryGetVisitor(out var visitor))
				{
					visitor.Visit(this, m);
					return m;
				}

				var me = (MemberExpression)m.Expression;

				if (me.Expression is ConstantExpression ce1)
				{
					var value = me.Member.GetMemberValue(ce1.Value);

					Context.TryAddParam(m.Member, value);
				}
				else
				{
					if (m.Member.Name == Extensions.IdColName)
					{
						if (me.Member.DeclaringType.IsAutoGenerated())
						{
							if (me.Expression is ParameterExpression)
							{
								Curr.Column(GetAlias(me.GetMemberName()), m.Member.Name);
							}
							else
								Curr.Column(me.Member.Name, m.Member.Name);
						}
						else
						{
							var flat = TryFlattenInnerSchema(me, me.Member.Name);
							if (flat is not null)
								Curr.Column(flat.Value.alias, flat.Value.column);
							else
							{
								var owner = GetAlias(me.GetMemberName());
								Curr.Column(owner, me.Member.Name);
							}
						}
					}
					else
					{
						if (me.Type.IsAutoGenerated())
						{
							var owner = GetAlias(m.GetMemberName());

							// TODO
							if (owner == "Priority")
								owner = "er";

							if (owner == m.Member.Name)
								Curr.All(owner);
							else
								Curr.Column(owner, m.Member.Name);
						}
						else if (me.Expression is ParameterExpression pe && me.Member.DeclaringType.IsAutoGenerated() && !me.Member.GetMemberType().IsAutoGenerated() && !pe.Name.StartsWithIgnoreCase("<"))
							Curr.Column(pe.Name, m.Member.Name);
						else
						{
							if (Context.Members.TryGetValue((me.Expression.Type, me.Member), out var exp1))
								me = exp1;

							// InnerSchema: entity.ComplexProp.SubProp → flattened column "e"."ComplexPropSubProp"
							// Supports multi-level nesting (e.g., entity.Address.GeoCoord.Lat)
							var flat = TryFlattenInnerSchema(me, m.Member.Name);
							if (flat is not null)
								Curr.Column(flat.Value.alias, flat.Value.column);
							else
							{
								// RelationSingle navigation traversal to a non-Id column (e.g., x.Person.Name).
								// Register an implicit INNER JOIN so the alias used here resolves at SQL level.
								var navAlias = TryEnsureImplicitJoin(me) ?? me.Member.Name;
								Curr.Column(navAlias, m.Member.Name);
							}
						}
					}
				}
			}
			else
			{
				if (m.Member.TryGetVisitor(out var visitor))
				{
					visitor.Visit(this, m);
					return m;
				}

				var columns = Context.IsWhere && m.Member.GetMemberType() != typeof(long?) ? Context.GetColumns(m.Member, default, default, true) : null;

				if (columns is null)
				{
					var name = GetAlias(m.GetMemberName());

					if (name == m.Member.Name)
						Curr.All(name);
					else
					{
						Curr.Column(name, m.Member.Name);
					}
				}
				else
				{
					var arr = columns.ToArray();

					if (arr.Length != 1)
						throw new InvalidOperationException();

					arr[0].Item1.CopyTo(Curr);
				}
			}

			return m;
		}
		else
		{
			if (m.Member.TryGetVisitor(out var visitor))
			{
				visitor.Visit(this, m);
				return m;
			}
			else
			{

			}
		}

		throw new NotSupportedException($"The member '{m.Member.Name}' is not supported");
	}

	/// <summary>
	/// Walks up a MemberExpression chain collecting inner schema (value object) prefixes.
	/// Returns (alias, flattenedColumnName) if inner schemas found, null otherwise.
	/// </summary>
	private (string alias, string column)? TryFlattenInnerSchema(MemberExpression startExpr, string leafName)
	{
		var parts = new List<string> { leafName };
		var current = startExpr;

		while (current is not null)
		{
			var memberType = current.Member.GetMemberType();
			var isInnerSchema = !memberType.IsNullable()
				&& !memberType.IsSerializablePrimitive()
				&& !memberType.IsAutoGenerated()
				&& !SchemaRegistry.TryGet(memberType, out _)
				&& current.Member.GetAttribute<RelationSingleAttribute>() is null;

			if (isInnerSchema)
				parts.Add(current.Member.Name);

			if (current.Expression is ParameterExpression)
			{
				if (parts.Count > 1)
				{
					parts.Reverse();
					return (GetAlias(current.GetMemberName()), string.Concat(parts));
				}

				return null;
			}

			current = current.Expression as MemberExpression;
		}

		return null;
	}

	/// <summary>
	/// Registers an implicit INNER JOIN for a RelationSingle navigation member
	/// (e.g., x.Person → join target table on PK = parent FK). Idempotent: a join
	/// for the same alias is registered only once. Returns the alias of the joined
	/// table, or null if the member is not a RelationSingle to a registered entity.
	/// </summary>
	private string TryEnsureImplicitJoin(MemberExpression nav)
	{
		if (nav?.Member.GetAttribute<RelationSingleAttribute>() is null)
			return null;

		var navType = nav.Member.GetMemberType();
		if (!SchemaRegistry.TryGet(navType, out var navSchema) || navSchema.Identity is null)
			return null;

		var alias = nav.Member.Name;

		if (Context.JoinParts.Any(j => j.tableAlias.EqualsIgnoreCase(alias)))
			return alias;

		// Resolve the alias of the table that owns the FK column. For chained
		// navigations (a.B.C.X), recursively register the upstream join first.
		string parentAlias;
		if (nav.Expression is ParameterExpression)
			parentAlias = Context.TableAlias;
		else if (nav.Expression is MemberExpression parentMe)
			parentAlias = TryEnsureImplicitJoin(parentMe) ?? Context.TableAlias;
		else
			parentAlias = Context.TableAlias;

		var joinPart = new Query();
		joinPart
			.InnerJoin()
			.Table(navSchema.Name, alias)
			.On()
			.Column(alias, navSchema.Identity.Name)
			.Equal()
			.Column(parentAlias, nav.Member.Name)
			.NewLine();

		Context.JoinParts.Add((alias, joinPart));

		return alias;
	}

	private void ParseOrderByExpression(MethodCallExpression expression, bool asc)
	{
		var curr = Curr;

		Curr = Context.OrderByPart;

		try
		{
			var lambdaExpression = expression.Arguments[1].GetOperand();
			var lambdaBody = lambdaExpression.Body;

			// Expression<Func<T, object>> over a value-type member emits Convert(member, object).
			if (lambdaBody is UnaryExpression { NodeType: ExpressionType.Convert or ExpressionType.ConvertChecked } conv)
				lambdaBody = conv.Operand;

			if (lambdaBody is MemberExpression body)
			{
				// When ordering by navigation property's Id (e.g., t.Person.Id),
				// use the FK property (Person) instead of the leaf member (Id).
				if (body.Member.Name == Extensions.IdColName
					&& body.Expression is MemberExpression navExpr
					&& !navExpr.Member.DeclaringType.IsAutoGenerated())
				{
					Context.OrderBy.Insert(0, (navExpr.Member, asc));
				}
				else
				{
					Context.OrderBy.Insert(0, (body.Member, asc));
				}
			}
			else if (lambdaBody is MethodCallExpression call)
			{
				if (!call.Method.TryGetVisitor(out var visitor))
					throw new NotSupportedException();

				visitor.Visit(this, call);

				if (!asc)
					Curr.Desc();
			}
			else
				throw new NotSupportedException();
		}
		finally
		{
			Curr = curr;
		}
	}
}