namespace Ecng.Data.Sql;

static class Extensions
{
	public const string IdColName = "Id";
	public const string DefaultAlias = "e";

	public static string GetMemberName(this MemberExpression exp)
	{
		string GetParamName(ParameterExpression pe)
			=> pe.Type.IsAutoGenerated() && pe.Name.Length > 3 ? exp.Member.Name : pe.Name;

		if (exp.Expression is ParameterExpression pe)
			return GetParamName(pe);
		else
		{
			if (exp.Expression.NodeType == ExpressionType.Convert)
				return GetParamName((ParameterExpression)((UnaryExpression)exp.Expression).Operand);

			var me = (MemberExpression)exp.Expression;

			return me.Type.IsAutoGenerated()
				? exp.Member.Name
				: GetMemberName(me);
		}
	}

	public static LambdaExpression GetOperand(this Expression exp)
		=> exp is LambdaExpression le ? le : (LambdaExpression)((UnaryExpression)exp).Operand;

	public static bool IsNullConstant(this Expression exp)
	{
		if (exp is ConstantExpression ce && ce.Value is null)
			return true;

		if (exp is MemberExpression me && me.Expression is ConstantExpression ce1)
		{
			var value = me.Member.GetMemberValue(ce1.Value);
			return value is null;
		}

		return false;
	}

	public static void RenderFuncCall(this ExpressionQueryTranslator translator, Query query, MethodCallExpression m, SqlExternalAttribute attr)
	{
		query.Raw($"dbo.{attr.Name.IsEmpty(m.Method.Name)}");
		query.OpenBracket();

		var isFirst = true;

		foreach (var arg in m.Arguments)
		{
			if (isFirst)
				isFirst = false;
			else
				query.Comma();

			translator.Visit(arg);
		}

		query.CloseBracket();
	}

	public static object GetId(this Expression exp)
	{
		var mce = (MethodCallExpression)exp;
		var me = (MemberExpression)((BinaryExpression)((LambdaExpression)mce.Arguments[1].StripQuotes()).Body).Right;

		return me.Member.GetMemberValue(me.Expression.GetConstant<object>());
	}

	public static Expression TryHandleImplicit(this Expression exp)
	{
		if (exp is MethodCallExpression opImplicit && opImplicit.Method.Name == "op_Implicit")
			exp = opImplicit.Arguments[0];

		return exp;
	}
}