namespace Ecng.Tests.Drawing;

using System;
using System.Drawing;
using System.IO;
using System.IO.Compression;
using System.Linq;

using Ecng.Drawing;

[TestClass]
public class ImageHelperTests : BaseTestClass
{
	// Image fixtures are embedded bytes, not generated by a third-party image library.
	// Solid black PNG and JPEG/GIF were exported once and checked for independent decoding.
	private static readonly byte[] _png = Convert.FromBase64String(
		"iVBORw0KGgoAAAANSUhEUgAAAUAAAACgCAIAAADywSLLAAAAq0lEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACvBli+AAGaPK0yAAAAAElFTkSuQmCC");

	private static readonly byte[] _jpeg = Convert.FromBase64String(
		"/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/wAALCAAwAGABAREA/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/9oACAEBAAA/AJ/AAAAAAAAAAAAAAAAAAAAAAAB//9k=");

	private static readonly byte[] _gif = Convert.FromBase64String(
		"R0lGODdhYAAwAIEAAAAAAAAAAAAAAAAAACwAAAAAYAAwAEAIbwABCBxIsKDBgwgTKlzIsKHDhxAjSpxIsaLFixgzatzIsaPHjyBDihxJsqTJkyhTqlzJsqXLlzBjypxJs6bNmzhz6tzJs6fPn0CDCh1KtKjRo0iTKl3KtKnTp1CjSp1KtarVq1izat3KtavXrzADAgA7");

	private static readonly byte[] _transparentPng = Convert.FromBase64String(
		"iVBORw0KGgoAAAANSUhEUgAAAAgAAAAGCAYAAAD+Bd/7AAAAFUlEQVR42mPkktNgwAeYGAiAwaAAAEKMAFwjCOSSAAAAAElFTkSuQmCC");

	[TestMethod]
	public void GetImageSize_PngWorksOnEveryPlatform()
	{
		_png.GetImageSize().AssertEqual(new Size(320, 160));

		ReadOnlySpan<byte> span = _transparentPng;
		span.GetImageSize().AssertEqual(new Size(8, 6));
	}

	[TestMethod]
	public void GetImageSize_JpegOnWindows()
	{
		if (OperatingSystem.IsWindows())
			_jpeg.GetImageSize().AssertEqual(new Size(96, 48));
		else
			ThrowsExactly<PlatformNotSupportedException>(() => _jpeg.GetImageSize());
	}

	[TestMethod]
	public void GetImageSize_BadDimensionsAndNullAreRejected()
	{
		byte[] missing = null;
		ThrowsExactly<ArgumentNullException>(() => missing.GetImageSize());

		var invalid = (byte[])_png.Clone();
		invalid[16] = invalid[17] = invalid[18] = invalid[19] = 0;
		ThrowsExactly<InvalidDataException>(() => invalid.GetImageSize());
	}

	[TestMethod]
	public void ResizeImage_FitsWithinBoundsAndPreservesAspectRatio()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var source = (byte[])_png.Clone();
		var reduced = source.ResizeImage(120, 100);

		reduced.GetPngSize().AssertEqual(new Size(120, 60));
		source.GetPngSize().AssertEqual(new Size(320, 160));
		source.SequenceEqual(_png).AssertTrue();

		_png.ResizeImage(50, 5).GetPngSize().AssertEqual(new Size(10, 5));
		_png.ResizeImage(2, 2).GetPngSize().AssertEqual(new Size(2, 1));
	}

	[TestMethod]
	public void ResizeImage_NeverUpscalesAndReturnsAnIndependentCopy()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var copy = _png.ResizeImage(1000, 1000);
		copy.SequenceEqual(_png).AssertTrue();
		ReferenceEquals(copy, _png).AssertFalse();
	}

	[TestMethod]
	public void ResizeImage_PreservesJpegAndGifEncoding()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var jpeg = _jpeg.ResizeImage(24, 24);
		(jpeg[0] == 0xff && jpeg[1] == 0xd8).AssertTrue();
		jpeg.GetImageSize().AssertEqual(new Size(24, 12));

		var gif = _gif.ResizeImage(48, 48);
		(gif[0] == (byte)'G' && gif[1] == (byte)'I' && gif[2] == (byte)'F').AssertTrue();
		gif.GetImageSize().AssertEqual(new Size(48, 24));
	}

	[TestMethod]
	public void ResizeImage_RejectsNonPositiveBounds()
	{
		ThrowsExactly<ArgumentOutOfRangeException>(() => _png.ResizeImage(0, 10));
		ThrowsExactly<ArgumentOutOfRangeException>(() => _png.ResizeImage(10, -1));

		byte[] missing = null;
		ThrowsExactly<ArgumentNullException>(() => missing.ResizeImage(1, 1));
	}

	[TestMethod]
	public void ConvertToPng_ConvertsJpegAndGif()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var jpeg = _jpeg.ConvertToPng();
		jpeg.IsPng().AssertTrue();
		jpeg.GetPngSize().AssertEqual(new Size(96, 48));

		var gif = _gif.ConvertToPng();
		gif.IsPng().AssertTrue();
		gif.GetPngSize().AssertEqual(new Size(96, 48));
	}

	[TestMethod]
	public void ConvertToPng_KeepsTransparentPixel()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var result = _transparentPng.ConvertToPng();
		result.GetPngSize().AssertEqual(new Size(8, 6));

		// Input is RGBA. The first PNG scanline contains filter + first RGBA pixel.
		// None/Sub/Up/Average/Paeth all leave the first pixel unchanged on the first row.
		result[25].AssertEqual((byte)6);
		var inflated = InflatePngImageData(result);
		inflated.Length.AssertEqual(6 * (1 + 8 * 4));
		inflated[4].AssertEqual((byte)0);
	}

	[TestMethod]
	public void ConvertToPng_NullAndUnsupportedFormat()
	{
		byte[] missing = null;
		ThrowsExactly<ArgumentNullException>(() => missing.ConvertToPng());

		if (OperatingSystem.IsWindows())
			ThrowsExactly<NotSupportedException>(() => new byte[] { 1, 2, 3 }.ConvertToPng());
	}

	[TestMethod]
	public void AddTextWatermark_DefaultVerdanaAndUnchangedSource()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var source = (byte[])_png.Clone();
		var result = source.AddTextWatermark("StockSharp");

		result.IsPng().AssertTrue();
		result.GetPngSize().AssertEqual(new Size(320, 160));
		source.SequenceEqual(_png).AssertTrue();
	}

	[TestMethod]
	public void AddTextWatermark_OpacityActuallyChangesPixels()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var hidden = _png.AddTextWatermark("StockSharp", opacity: 0);
		var visible = _png.AddTextWatermark("StockSharp", opacity: 255);

		hidden.SequenceEqual(visible).AssertFalse();
	}

	[TestMethod]
	public void AddTextWatermark_LongTextFitsWithoutChangingDimensions()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var result = _png.AddTextWatermark("A moderately long watermark that needs resizing", fontSize: 45, margin: 8);
		result.GetPngSize().AssertEqual(new Size(320, 160));
	}

	[TestMethod]
	public void AddTextWatermark_ConvertsJpegToPng()
	{
		if (!OperatingSystem.IsWindows())
			return;

		var result = _jpeg.AddTextWatermark("Test", fontSize: 18, margin: 2);
		result.IsPng().AssertTrue();
		result.GetPngSize().AssertEqual(new Size(96, 48));
	}

	[TestMethod]
	public void AddTextWatermark_ValidatesArguments()
	{
		ThrowsExactly<ArgumentException>(() => _png.AddTextWatermark(" "));
		ThrowsExactly<ArgumentOutOfRangeException>(() => _png.AddTextWatermark("Test", fontSize: 0));
		ThrowsExactly<ArgumentOutOfRangeException>(() => _png.AddTextWatermark("Test", fontSize: float.NaN));
		ThrowsExactly<ArgumentOutOfRangeException>(() => _png.AddTextWatermark("Test", fontSize: float.PositiveInfinity));
		ThrowsExactly<ArgumentOutOfRangeException>(() => _png.AddTextWatermark("Test", margin: -1));
		ThrowsExactly<ArgumentException>(() => _png.AddTextWatermark("Test", fontFamily: " "));

		byte[] missing = null;
		ThrowsExactly<ArgumentNullException>(() => missing.AddTextWatermark("Test"));

		if (OperatingSystem.IsWindows())
		{
			ThrowsExactly<ArgumentOutOfRangeException>(() => _png.AddTextWatermark("Test", margin: 300));
			ThrowsExactly<InvalidOperationException>(() => _png.AddTextWatermark("Test", fontFamily: "NonexistentEcngFont777"));
		}
	}

	[TestMethod]
	public void UnsupportedPlatform_ReportsItExplicitly()
	{
		if (OperatingSystem.IsWindows())
			return;

		ThrowsExactly<PlatformNotSupportedException>(() => _png.ResizeImage(100, 100));
		ThrowsExactly<PlatformNotSupportedException>(() => _jpeg.ConvertToPng());
		ThrowsExactly<PlatformNotSupportedException>(() => _png.AddTextWatermark("Hello"));
	}

	[TestMethod]
	public void UnsupportedCodec_IsNotSilentlyAccepted()
	{
		if (!OperatingSystem.IsWindows())
			return;

		ThrowsExactly<NotSupportedException>(() => new byte[] { (byte)'I', (byte)'I', 42, 0 }.ResizeImage(1, 1));
		ThrowsExactly<NotSupportedException>(() => new byte[] { (byte)'I', (byte)'I', 42, 0 }.ConvertToPng());
	}

	// This decoder is deliberately test-only and verifies actual PNG alpha pixel bytes.
	private static byte[] InflatePngImageData(byte[] png)
	{
		using var compressed = new MemoryStream();
		var at = 8;

		while (at + 12 <= png.Length)
		{
			var size = ((uint)png[at] << 24) | ((uint)png[at + 1] << 16) | ((uint)png[at + 2] << 8) | png[at + 3];
			var dataStart = at + 8;
			if (size > png.Length - dataStart - 4)
				throw new InvalidDataException("Invalid PNG chunk length.");

			if (png[at + 4] == (byte)'I' && png[at + 5] == (byte)'D' && png[at + 6] == (byte)'A' && png[at + 7] == (byte)'T')
				compressed.Write(png, dataStart, (int)size);

			at = dataStart + (int)size + 4;
		}

		compressed.Position = 0;
		using var inflated = new MemoryStream();
		using (var zlib = new ZLibStream(compressed, CompressionMode.Decompress, leaveOpen: true))
			zlib.CopyTo(inflated);

		return inflated.ToArray();
	}
}
