//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecng.Data.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecng.Data.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add
        ///except
        ///percent
        ///all
        ///exec
        ///plan
        ///alter
        ///execute
        ///precision
        ///and
        ///exists
        ///primary
        ///any
        ///exit
        ///print
        ///as
        ///fetch
        ///proc
        ///asc
        ///file
        ///procedure
        ///authorization
        ///fillfactor
        ///public
        ///backup
        ///for
        ///raiserror
        ///begin
        ///foreign
        ///read
        ///between
        ///freetext
        ///readtext
        ///break
        ///freetexttable
        ///reconfigure
        ///browse
        ///from
        ///references
        ///bulk
        ///full
        ///replication
        ///by
        ///function
        ///restore
        ///cascade
        ///goto
        ///restrict
        ///case
        ///grant
        ///return
        ///check
        ///group
        ///revoke
        ///checkpoint
        ///having
        ///right
        ///close
        ///holdlock
        ///rollback
        ///clustered
        ///identity
        ///rowco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlServerReservedWords {
            get {
                return ResourceManager.GetString("SqlServerReservedWords", resourceCulture);
            }
        }
    }
}
