<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\common.props" />
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Text.Encoding.CodePages" Version="$(MsExtensionsVer)" />

    <PackageReference Include="Nito.AsyncEx" Version="$(NitoVer)" />
    <PackageReference Include="SmartFormat" Version="$(SmartFormatVer)" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="Microsoft.Bcl.TimeProvider" Version="$(BclTimeProviderVer)" />
  </ItemGroup>
<ItemGroup>
    <EmbeddedResource Include="TimeZoneConverter\Data\*.csv.gz" />
  </ItemGroup>
</Project>