#if NET10_0_OR_GREATER

namespace Ecng.Tests.Data;

using System.Text.RegularExpressions;

using Ecng.Data;
using Ecng.Data.Sql;
using Ecng.Serialization;

/// <summary>
/// Pure (no-database) checks over the <see cref="SchemaMigrator.Compare"/> +
/// <see cref="SchemaMigrator.GenerateMigrationSql"/> pipeline.
/// </summary>
[TestClass]
public class SchemaMigratorSqlTests : BaseTestClass
{
	// Standalone carrier types — the schemas below are built by hand so the
	// test does not depend on reflection/attribute discovery.
	private sealed class DupFkFile
	{
		public long Id { get; set; }
	}

	private sealed class DupFkProvider
	{
		public long Id { get; set; }
		public long Picture { get; set; }
	}

	private static (Schema provider, Schema file) BuildSchemas()
	{
		var file = new Schema
		{
			TableName = "File",
			EntityType = typeof(DupFkFile),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new DupFkFile(),
		};

		var provider = new Schema
		{
			TableName = "DnsProvider",
			EntityType = typeof(DupFkProvider),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns =
			[
				new SchemaColumn
				{
					Name = "Picture",
					ClrType = typeof(long),
					IsNullable = true,
					ReferencedEntityType = typeof(DupFkFile),
				},
			],
			Factory = () => new DupFkProvider(),
		};

		// ResolveForeignKeyTarget reads the referenced entity's schema from the
		// registry, so the File side must be registered before comparing.
		SchemaRegistry.Register(file);
		SchemaRegistry.Register(provider);

		return (provider, file);
	}

	/// <summary>
	/// Regression: adding a brand-new foreign-key column emitted the
	/// <c>ALTER TABLE … ADD CONSTRAINT</c> twice. The MissingColumn branch
	/// already creates the column together with its FOREIGN KEY, while
	/// AppendForeignKeyDiffs independently raised a MissingForeignKey diff for
	/// the same column — so the constraint was generated by both paths. The
	/// FK backfill must skip columns that do not yet exist in the database
	/// (they are owned by the MissingColumn branch), leaving a single
	/// constraint statement.
	/// </summary>
	[TestMethod]
	public void NewForeignKeyColumn_EmitsConstraintOnce()
	{
		var (provider, file) = BuildSchemas();
		var dialect = SqlServerDialect.Instance;

		// DB state: both tables exist with their Id, but DnsProvider.Picture is
		// a new column not yet present — and there is no FK constraint at all.
		var dbColumns = new List<DbColumnInfo>
		{
			new("DnsProvider", "Id", "bigint", false, null, null, null),
			new("File", "Id", "bigint", false, null, null, null),
		};

		var diffs = SchemaMigrator.Compare(
			[provider, file],
			dbColumns,
			dialect,
			skipComputed: false,
			dbForeignKeys: []);

		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [provider, file]);

		// The FK column is added once, and its constraint must appear exactly once.
		Regex.Matches(sql, "ADD CONSTRAINT", RegexOptions.IgnoreCase).Count.AssertEqual(
			1,
			$"Expected a single ADD CONSTRAINT for the new FK column. " +
			$"Diffs: [{string.Join(", ", diffs.Select(d => $"{d.Kind} {d.TableName}.{d.ColumnName}"))}]. " +
			$"Generated SQL: {sql}");

		sql.Contains("FK_DnsProvider_Picture").AssertTrue(
			$"Expected the FK constraint on DnsProvider.Picture, got: {sql}");
	}

	private sealed class DropOrderSocial
	{
		public long Id { get; set; }
	}

	/// <summary>
	/// Regression: the commented-out drop script must be runnable as-is. A column
	/// carrying a foreign key cannot be dropped while the constraint still binds
	/// it, so the <c>DROP CONSTRAINT</c> must be emitted before the matching
	/// <c>DROP COLUMN</c> (the diff order produced ExtraColumn before
	/// ExtraForeignKey, yielding the wrong order).
	/// </summary>
	[TestMethod]
	public void ExtraForeignKeyColumn_DropsConstraintBeforeColumn()
	{
		var dialect = SqlServerDialect.Instance;

		var social = new Schema
		{
			TableName = "Social",
			EntityType = typeof(DropOrderSocial),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new DropOrderSocial(),
		};

		// DB has two extra FK columns the model no longer declares, each backed by a constraint.
		var dbColumns = new List<DbColumnInfo>
		{
			new("Social", "Id", "bigint", false, null, null, null),
			new("Social", "AuthDomainOnly", "bigint", true, null, null, null),
			new("Social", "MainPageDomain", "bigint", true, null, null, null),
		};

		var dbForeignKeys = new List<DbForeignKeyInfo>
		{
			new("FK_Social_AuthDomainOnly", "Social", "AuthDomainOnly", "Domain", "Id"),
			new("FK_Social_MainPageDomain", "Social", "MainPageDomain", "Domain", "Id"),
		};

		var diffs = SchemaMigrator.Compare([social], dbColumns, dialect, skipComputed: false, dbForeignKeys: dbForeignKeys);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [social]);

		var firstConstraint = sql.IndexOf("DROP CONSTRAINT", StringComparison.OrdinalIgnoreCase);
		var firstColumn = sql.IndexOf("DROP COLUMN", StringComparison.OrdinalIgnoreCase);

		(firstConstraint >= 0).AssertTrue($"Expected a DROP CONSTRAINT, got: {sql}");
		(firstColumn >= 0).AssertTrue($"Expected a DROP COLUMN, got: {sql}");
		(firstConstraint < firstColumn).AssertTrue(
			$"A column's FK constraint must be dropped before the column itself. Got: {sql}");
	}

	/// <summary>
	/// Regression: an extra table cannot be dropped while a foreign key still
	/// references it, so every <c>DROP CONSTRAINT</c> must precede the
	/// <c>DROP TABLE</c> (the diff order produced ExtraTable before
	/// ExtraForeignKey, yielding the wrong order).
	/// </summary>
	[TestMethod]
	public void ExtraTableWithForeignKey_DropsConstraintBeforeTable()
	{
		var dialect = SqlServerDialect.Instance;

		var social = new Schema
		{
			TableName = "Social",
			EntityType = typeof(DropOrderSocial),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new DropOrderSocial(),
		};

		// 'Orphan' is a DB-only table with a FK referencing 'Social'.
		var dbColumns = new List<DbColumnInfo>
		{
			new("Social", "Id", "bigint", false, null, null, null),
			new("Orphan", "Id", "bigint", false, null, null, null),
			new("Orphan", "SocialId", "bigint", true, null, null, null),
		};

		var dbForeignKeys = new List<DbForeignKeyInfo>
		{
			new("FK_Orphan_SocialId", "Orphan", "SocialId", "Social", "Id"),
		};

		var diffs = SchemaMigrator.Compare([social], dbColumns, dialect, skipComputed: false,
			dbForeignKeys: dbForeignKeys, detectExtraTables: true);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [social]);

		var firstConstraint = sql.IndexOf("DROP CONSTRAINT", StringComparison.OrdinalIgnoreCase);
		var firstTable = sql.IndexOf("DROP TABLE", StringComparison.OrdinalIgnoreCase);

		(firstConstraint >= 0).AssertTrue($"Expected a DROP CONSTRAINT, got: {sql}");
		(firstTable >= 0).AssertTrue($"Expected a DROP TABLE, got: {sql}");
		(firstConstraint < firstTable).AssertTrue(
			$"Foreign keys must be dropped before the table they belong to. Got: {sql}");
	}
}

#endif
