#if NET10_0_OR_GREATER

namespace Ecng.Tests.Data;

using System.Text.RegularExpressions;

using Ecng.Data;
using Ecng.Data.Sql;
using Ecng.Serialization;

/// <summary>
/// Pure (no-database) checks over the <see cref="SchemaMigrator.Compare"/> +
/// <see cref="SchemaMigrator.GenerateMigrationSql"/> pipeline.
/// </summary>
[TestClass]
public class SchemaMigratorSqlTests : BaseTestClass
{
	// Standalone carrier types — the schemas below are built by hand so the
	// test does not depend on reflection/attribute discovery.
	private sealed class DupFkFile
	{
		public long Id { get; set; }
	}

	private sealed class DupFkProvider
	{
		public long Id { get; set; }
		public long Picture { get; set; }
	}

	private static (Schema provider, Schema file) BuildSchemas()
	{
		var file = new Schema
		{
			TableName = "File",
			EntityType = typeof(DupFkFile),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new DupFkFile(),
		};

		var provider = new Schema
		{
			TableName = "DnsProvider",
			EntityType = typeof(DupFkProvider),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns =
			[
				new SchemaColumn
				{
					Name = "Picture",
					ClrType = typeof(long),
					IsNullable = true,
					ReferencedEntityType = typeof(DupFkFile),
				},
			],
			Factory = () => new DupFkProvider(),
		};

		// ResolveForeignKeyTarget reads the referenced entity's schema from the
		// registry, so the File side must be registered before comparing.
		SchemaRegistry.Register(file);
		SchemaRegistry.Register(provider);

		return (provider, file);
	}

	/// <summary>
	/// Regression: adding a brand-new foreign-key column emitted the
	/// <c>ALTER TABLE … ADD CONSTRAINT</c> twice. The MissingColumn branch
	/// already creates the column together with its FOREIGN KEY, while
	/// AppendForeignKeyDiffs independently raised a MissingForeignKey diff for
	/// the same column — so the constraint was generated by both paths. The
	/// FK backfill must skip columns that do not yet exist in the database
	/// (they are owned by the MissingColumn branch), leaving a single
	/// constraint statement.
	/// </summary>
	[TestMethod]
	public void NewForeignKeyColumn_EmitsConstraintOnce()
	{
		var (provider, file) = BuildSchemas();
		var dialect = SqlServerDialect.Instance;

		// DB state: both tables exist with their Id, but DnsProvider.Picture is
		// a new column not yet present — and there is no FK constraint at all.
		var dbColumns = new List<DbColumnInfo>
		{
			new("DnsProvider", "Id", "bigint", false, null, null, null),
			new("File", "Id", "bigint", false, null, null, null),
		};

		var diffs = SchemaMigrator.Compare(
			[provider, file],
			dbColumns,
			dialect,
			skipComputed: false,
			dbForeignKeys: []);

		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [provider, file]);

		// The FK column is added once, and its constraint must appear exactly once.
		Regex.Matches(sql, "ADD CONSTRAINT", RegexOptions.IgnoreCase).Count.AssertEqual(
			1,
			$"Expected a single ADD CONSTRAINT for the new FK column. " +
			$"Diffs: [{string.Join(", ", diffs.Select(d => $"{d.Kind} {d.TableName}.{d.ColumnName}"))}]. " +
			$"Generated SQL: {sql}");

		sql.Contains("FK_DnsProvider_Picture").AssertTrue(
			$"Expected the FK constraint on DnsProvider.Picture, got: {sql}");
	}

	private sealed class FkParent
	{
		public long Id { get; set; }
	}

	private sealed class FkChild
	{
		public long Id { get; set; }
		public long ParentId { get; set; }
	}

	// Two brand-new tables where FkChild has a FOREIGN KEY to FkParent. Returned
	// child-first on purpose so the migrator cannot rely on caller ordering.
	private static (Schema child, Schema parent) BuildNewFkSchemas()
	{
		var parent = new Schema
		{
			TableName = "FkParent",
			EntityType = typeof(FkParent),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new FkParent(),
		};

		var child = new Schema
		{
			TableName = "FkChild",
			EntityType = typeof(FkChild),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns =
			[
				new SchemaColumn
				{
					Name = "ParentId",
					ClrType = typeof(long),
					IsNullable = false,
					ReferencedEntityType = typeof(FkParent),
				},
			],
			Factory = () => new FkChild(),
		};

		SchemaRegistry.Register(parent);
		SchemaRegistry.Register(child);

		return (child, parent);
	}

	/// <summary>
	/// For dialects that support ALTER TABLE ADD CONSTRAINT (SQL Server, PostgreSQL),
	/// a new table's foreign keys must be emitted as a separate statement AFTER every
	/// CREATE TABLE, not inline. That makes the script independent of table-creation
	/// order (and removes the need for callers to topologically pre-sort the tables).
	/// </summary>
	[DataRow("sqlserver")]
	[DataRow("postgres")]
	[TestMethod]
	public void NewTables_ForeignKey_DeferredAfterCreate_ForAlterDialects(string provider)
	{
		var dialect = provider == "postgres"
			? (ISqlDialect)PostgreSqlDialect.Instance
			: SqlServerDialect.Instance;

		var (child, parent) = BuildNewFkSchemas();

		// Both tables are missing from the DB.
		var diffs = SchemaMigrator.Compare([child, parent], [], dialect, skipComputed: false, dbForeignKeys: []);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [child, parent]);

		Regex.Matches(sql, "CREATE TABLE", RegexOptions.IgnoreCase).Count.AssertEqual(2,
			$"Both new tables must be created. SQL: {sql}");

		sql.Contains("ALTER TABLE", StringComparison.OrdinalIgnoreCase).AssertTrue(
			$"FK on a new table must be a deferred ALTER TABLE ADD CONSTRAINT. SQL: {sql}");

		var lastCreate = sql.LastIndexOf("CREATE TABLE", StringComparison.OrdinalIgnoreCase);
		var fk = sql.IndexOf("FOREIGN KEY", StringComparison.OrdinalIgnoreCase);

		(fk > lastCreate).AssertTrue(
			$"The FOREIGN KEY must be added after both CREATE TABLE statements, not inline. SQL: {sql}");

		Regex.Matches(sql, "FOREIGN KEY", RegexOptions.IgnoreCase).Count.AssertEqual(1,
			$"Exactly one FK constraint expected. SQL: {sql}");
	}

	/// <summary>
	/// SQLite cannot ALTER TABLE ADD CONSTRAINT a foreign key, so the FK must stay
	/// inline inside CREATE TABLE. That forces a topological order: the referenced
	/// table (FkParent) has to be created before the referencing one (FkChild), even
	/// when the schemas are supplied child-first.
	/// </summary>
	[TestMethod]
	public void NewTables_ForeignKey_InlineAndOrdered_ForSqlite()
	{
		var dialect = SQLiteDialect.Instance;

		var (child, parent) = BuildNewFkSchemas();

		var diffs = SchemaMigrator.Compare([child, parent], [], dialect, skipComputed: false, dbForeignKeys: []);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [child, parent]);

		sql.Contains("ALTER TABLE", StringComparison.OrdinalIgnoreCase).AssertFalse(
			$"SQLite must not emit ALTER TABLE ADD CONSTRAINT for a FK. SQL: {sql}");

		sql.Contains("FOREIGN KEY", StringComparison.OrdinalIgnoreCase).AssertTrue(
			$"SQLite must keep the FK inline in CREATE TABLE. SQL: {sql}");

		var parentPos = sql.IndexOf(dialect.QuoteIdentifier("FkParent"), StringComparison.Ordinal);
		var childPos = sql.IndexOf(dialect.QuoteIdentifier("FkChild"), StringComparison.Ordinal);

		(parentPos >= 0 && childPos >= 0).AssertTrue($"Both tables must be present. SQL: {sql}");
		(parentPos < childPos).AssertTrue(
			$"The referenced table FkParent must be created before FkChild. SQL: {sql}");
	}

	private sealed class DropOrderSocial
	{
		public long Id { get; set; }
	}

	/// <summary>
	/// Regression: the commented-out drop script must be runnable as-is. A column
	/// carrying a foreign key cannot be dropped while the constraint still binds
	/// it, so the <c>DROP CONSTRAINT</c> must be emitted before the matching
	/// <c>DROP COLUMN</c> (the diff order produced ExtraColumn before
	/// ExtraForeignKey, yielding the wrong order).
	/// </summary>
	[TestMethod]
	public void ExtraForeignKeyColumn_DropsConstraintBeforeColumn()
	{
		var dialect = SqlServerDialect.Instance;

		var social = new Schema
		{
			TableName = "Social",
			EntityType = typeof(DropOrderSocial),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new DropOrderSocial(),
		};

		// DB has two extra FK columns the model no longer declares, each backed by a constraint.
		var dbColumns = new List<DbColumnInfo>
		{
			new("Social", "Id", "bigint", false, null, null, null),
			new("Social", "AuthDomainOnly", "bigint", true, null, null, null),
			new("Social", "MainPageDomain", "bigint", true, null, null, null),
		};

		var dbForeignKeys = new List<DbForeignKeyInfo>
		{
			new("FK_Social_AuthDomainOnly", "Social", "AuthDomainOnly", "Domain", "Id"),
			new("FK_Social_MainPageDomain", "Social", "MainPageDomain", "Domain", "Id"),
		};

		var diffs = SchemaMigrator.Compare([social], dbColumns, dialect, skipComputed: false, dbForeignKeys: dbForeignKeys);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [social]);

		var firstConstraint = sql.IndexOf("DROP CONSTRAINT", StringComparison.OrdinalIgnoreCase);
		var firstColumn = sql.IndexOf("DROP COLUMN", StringComparison.OrdinalIgnoreCase);

		(firstConstraint >= 0).AssertTrue($"Expected a DROP CONSTRAINT, got: {sql}");
		(firstColumn >= 0).AssertTrue($"Expected a DROP COLUMN, got: {sql}");
		(firstConstraint < firstColumn).AssertTrue(
			$"A column's FK constraint must be dropped before the column itself. Got: {sql}");
	}

	/// <summary>
	/// Regression: an extra table cannot be dropped while a foreign key still
	/// references it, so every <c>DROP CONSTRAINT</c> must precede the
	/// <c>DROP TABLE</c> (the diff order produced ExtraTable before
	/// ExtraForeignKey, yielding the wrong order).
	/// </summary>
	[TestMethod]
	public void ExtraTableWithForeignKey_DropsConstraintBeforeTable()
	{
		var dialect = SqlServerDialect.Instance;

		var social = new Schema
		{
			TableName = "Social",
			EntityType = typeof(DropOrderSocial),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new DropOrderSocial(),
		};

		// 'Orphan' is a DB-only table with a FK referencing 'Social'.
		var dbColumns = new List<DbColumnInfo>
		{
			new("Social", "Id", "bigint", false, null, null, null),
			new("Orphan", "Id", "bigint", false, null, null, null),
			new("Orphan", "SocialId", "bigint", true, null, null, null),
		};

		var dbForeignKeys = new List<DbForeignKeyInfo>
		{
			new("FK_Orphan_SocialId", "Orphan", "SocialId", "Social", "Id"),
		};

		var diffs = SchemaMigrator.Compare([social], dbColumns, dialect, skipComputed: false,
			dbForeignKeys: dbForeignKeys, detectExtraTables: true);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [social]);

		var firstConstraint = sql.IndexOf("DROP CONSTRAINT", StringComparison.OrdinalIgnoreCase);
		var firstTable = sql.IndexOf("DROP TABLE", StringComparison.OrdinalIgnoreCase);

		(firstConstraint >= 0).AssertTrue($"Expected a DROP CONSTRAINT, got: {sql}");
		(firstTable >= 0).AssertTrue($"Expected a DROP TABLE, got: {sql}");
		(firstConstraint < firstTable).AssertTrue(
			$"Foreign keys must be dropped before the table they belong to. Got: {sql}");
	}

	#region DateOnly / TimeOnly

	private sealed class Schedule
	{
		public long Id { get; set; }
		public DateOnly Day { get; set; }
		public TimeOnly OpensAt { get; set; }
		public DateOnly? Until { get; set; }
	}

	private static Schema BuildScheduleSchema() => new()
	{
		TableName = "Schedule",
		EntityType = typeof(Schedule),
		Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
		Columns =
		[
			new SchemaColumn { Name = "Day", ClrType = typeof(DateOnly) },
			new SchemaColumn { Name = "OpensAt", ClrType = typeof(TimeOnly) },
			new SchemaColumn { Name = "Until", ClrType = typeof(DateOnly?), IsNullable = true },
		],
		Factory = () => new Schedule(),
	};

	/// <summary>
	/// A new non-nullable column is added in three steps - add as NULL, backfill, then
	/// tighten to NOT NULL - and the backfill uses the dialect's default literal. For a
	/// DATE or TIME column an empty string is not merely a poor default: both SQL Server
	/// and PostgreSQL refuse to convert it, so the whole generated script fails to apply.
	/// </summary>
	[TestMethod]
	[DataRow("SqlServer")]
	[DataRow("PostgreSql")]
	public void MissingNotNullDateOnly_BackfillsWithAValidLiteral(string dialectName)
	{
		var dialect = GetDialect(dialectName);
		var schedule = BuildScheduleSchema();

		// The table exists but holds nothing except its identity.
		var dbColumns = new List<DbColumnInfo>
		{
			new("Schedule", "Id", "bigint", false, null, null, null),
		};

		var diffs = SchemaMigrator.Compare([schedule], dbColumns, dialect, skipComputed: false);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [schedule]);

		sql.Contains("'0001-01-01'").AssertTrue($"Expected a DATE backfill literal, got: {sql}");
		sql.Contains("'00:00:00'").AssertTrue($"Expected a TIME backfill literal, got: {sql}");
		sql.Contains("= N''").AssertFalse($"An empty string cannot be converted to DATE or TIME. Got: {sql}");
		sql.Contains("= ''").AssertFalse($"An empty string cannot be converted to DATE or TIME. Got: {sql}");
	}

	/// <summary>
	/// A nullable date needs no backfill at all, so the three-step path - and its literal -
	/// must not appear for one.
	/// </summary>
	[TestMethod]
	[DataRow("SqlServer")]
	[DataRow("PostgreSql")]
	public void MissingNullableDateOnly_AddsColumnWithoutBackfill(string dialectName)
	{
		var dialect = GetDialect(dialectName);

		var schedule = new Schema
		{
			TableName = "Schedule",
			EntityType = typeof(Schedule),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [new SchemaColumn { Name = "Until", ClrType = typeof(DateOnly?), IsNullable = true }],
			Factory = () => new Schedule(),
		};

		var dbColumns = new List<DbColumnInfo>
		{
			new("Schedule", "Id", "bigint", false, null, null, null),
		};

		var diffs = SchemaMigrator.Compare([schedule], dbColumns, dialect, skipComputed: false);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [schedule]);

		sql.Contains("UPDATE").AssertFalse($"A nullable column needs no backfill. Got: {sql}");
		sql.Contains("DATE").AssertTrue($"Expected the DATE column to be added, got: {sql}");
	}

	/// <summary>
	/// The column the dialect itself emits for a DateOnly/TimeOnly property must read back
	/// as matching that property. When it does not, every comparison reports the same
	/// difference forever and the tool keeps proposing a migration that changes nothing.
	/// </summary>
	[TestMethod]
	[DataRow("SqlServer", "date", "time")]
	[DataRow("PostgreSql", "date", "time without time zone")]
	[DataRow("SQLite", "DATE", "TIME")]
	public void LiveDateAndTimeColumns_MatchTheirProperties(string dialectName, string dateType, string timeType)
	{
		var dialect = GetDialect(dialectName);
		var schedule = BuildScheduleSchema();

		var dbColumns = new List<DbColumnInfo>
		{
			new("Schedule", "Id", dialectName == "SQLite" ? "INTEGER" : "bigint", false, null, null, null),
			new("Schedule", "Day", dateType, false, null, null, null),
			new("Schedule", "OpensAt", timeType, false, null, null, null),
			new("Schedule", "Until", dateType, true, null, null, null),
		};

		var diffs = SchemaMigrator.Compare([schedule], dbColumns, dialect, skipComputed: false);
		var mismatches = diffs.Where(d => d.Kind == SchemaDiffKind.TypeMismatch).ToArray();

		mismatches.Length.AssertEqual(0,
			$"Expected no type differences, got: {mismatches.Select(d => $"{d.ColumnName}").JoinComma()}");
	}

	/// <summary>
	/// A table created from scratch has to declare the temporal columns as such - this is
	/// the path a fresh deployment takes, where nothing exists to compare against.
	/// </summary>
	[TestMethod]
	[DataRow("SqlServer", "DATE", "TIME")]
	[DataRow("PostgreSql", "DATE", "TIME")]
	[DataRow("SQLite", "TEXT", "TEXT")]
	public void MissingTable_CreatesDateAndTimeColumns(string dialectName, string dateType, string timeType)
	{
		var dialect = GetDialect(dialectName);
		var schedule = BuildScheduleSchema();

		var diffs = SchemaMigrator.Compare([schedule], [], dialect, skipComputed: false);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [schedule]);

		sql.ContainsIgnoreCase("CREATE TABLE").AssertTrue($"Expected a CREATE TABLE, got: {sql}");
		sql.Contains($"{dateType} NOT NULL").AssertTrue($"Expected a non-nullable {dateType} column, got: {sql}");
		sql.Contains($"{timeType} NOT NULL").AssertTrue($"Expected a non-nullable {timeType} column, got: {sql}");
		sql.Contains($"{dateType} NULL").AssertTrue($"Expected a nullable {dateType} column, got: {sql}");
	}

	/// <summary>
	/// A date is a natural thing to index - a period lookup or a per-day uniqueness rule -
	/// and index emission reads the column through a different path than the definition.
	/// </summary>
	[TestMethod]
	[DataRow("SqlServer")]
	[DataRow("PostgreSql")]
	public void MissingIndexOnDateOnly_IsEmitted(string dialectName)
	{
		var dialect = GetDialect(dialectName);

		var schedule = new Schema
		{
			TableName = "Schedule",
			EntityType = typeof(Schedule),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns =
			[
				new SchemaColumn
				{
					Name = "Day",
					ClrType = typeof(DateOnly),
					IsIndex = true,
					Indexes = [new SchemaColumnIndex(null, 0)],
				},
			],
			Factory = () => new Schedule(),
		};

		var dbColumns = new List<DbColumnInfo>
		{
			new("Schedule", "Id", "bigint", false, null, null, null),
			new("Schedule", "Day", "date", false, null, null, null),
		};

		var diffs = SchemaMigrator.Compare([schedule], dbColumns, dialect, skipComputed: false, dbIndexes: []);
		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [schedule]);

		sql.ContainsIgnoreCase("CREATE INDEX").AssertTrue($"Expected an index on the date column, got: {sql}");
		sql.Contains("Day").AssertTrue($"Expected the index to name the column, got: {sql}");
	}

	#endregion

	private static ISqlDialect GetDialect(string name) => name switch
	{
		"SqlServer" => SqlServerDialect.Instance,
		"SQLite" => SQLiteDialect.Instance,
		"PostgreSql" => PostgreSqlDialect.Instance,
		_ => throw new ArgumentOutOfRangeException(nameof(name), name, "Unknown dialect."),
	};
}

#endif
