namespace Ecng.Tests.Data;

using System.Text.RegularExpressions;

using Ecng.Data;
using Ecng.Data.Sql;
using Ecng.Serialization;

/// <summary>
/// Pure (no-database) checks over the <see cref="SchemaMigrator.Compare"/> +
/// <see cref="SchemaMigrator.GenerateMigrationSql"/> pipeline.
/// </summary>
[TestClass]
public class SchemaMigratorSqlTests : BaseTestClass
{
	// Standalone carrier types — the schemas below are built by hand so the
	// test does not depend on reflection/attribute discovery.
	private sealed class DupFkFile
	{
		public long Id { get; set; }
	}

	private sealed class DupFkProvider
	{
		public long Id { get; set; }
		public long Picture { get; set; }
	}

	private static (Schema provider, Schema file) BuildSchemas()
	{
		var file = new Schema
		{
			TableName = "File",
			EntityType = typeof(DupFkFile),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns = [],
			Factory = () => new DupFkFile(),
		};

		var provider = new Schema
		{
			TableName = "DnsProvider",
			EntityType = typeof(DupFkProvider),
			Identity = new SchemaColumn { Name = "Id", ClrType = typeof(long), IsReadOnly = true },
			Columns =
			[
				new SchemaColumn
				{
					Name = "Picture",
					ClrType = typeof(long),
					IsNullable = true,
					ReferencedEntityType = typeof(DupFkFile),
				},
			],
			Factory = () => new DupFkProvider(),
		};

		// ResolveForeignKeyTarget reads the referenced entity's schema from the
		// registry, so the File side must be registered before comparing.
		SchemaRegistry.Register(file);
		SchemaRegistry.Register(provider);

		return (provider, file);
	}

	/// <summary>
	/// Regression: adding a brand-new foreign-key column emitted the
	/// <c>ALTER TABLE … ADD CONSTRAINT</c> twice. The MissingColumn branch
	/// already creates the column together with its FOREIGN KEY, while
	/// AppendForeignKeyDiffs independently raised a MissingForeignKey diff for
	/// the same column — so the constraint was generated by both paths. The
	/// FK backfill must skip columns that do not yet exist in the database
	/// (they are owned by the MissingColumn branch), leaving a single
	/// constraint statement.
	/// </summary>
	[TestMethod]
	public void NewForeignKeyColumn_EmitsConstraintOnce()
	{
		var (provider, file) = BuildSchemas();
		var dialect = SqlServerDialect.Instance;

		// DB state: both tables exist with their Id, but DnsProvider.Picture is
		// a new column not yet present — and there is no FK constraint at all.
		var dbColumns = new List<DbColumnInfo>
		{
			new("DnsProvider", "Id", "bigint", false, null, null, null),
			new("File", "Id", "bigint", false, null, null, null),
		};

		var diffs = SchemaMigrator.Compare(
			[provider, file],
			dbColumns,
			dialect,
			skipComputed: false,
			dbForeignKeys: []);

		var sql = SchemaMigrator.GenerateMigrationSql(dialect, diffs, [provider, file]);

		// The FK column is added once, and its constraint must appear exactly once.
		Regex.Matches(sql, "ADD CONSTRAINT", RegexOptions.IgnoreCase).Count.AssertEqual(
			1,
			$"Expected a single ADD CONSTRAINT for the new FK column. " +
			$"Diffs: [{string.Join(", ", diffs.Select(d => $"{d.Kind} {d.TableName}.{d.ColumnName}"))}]. " +
			$"Generated SQL: {sql}");

		sql.Contains("FK_DnsProvider_Picture").AssertTrue(
			$"Expected the FK constraint on DnsProvider.Picture, got: {sql}");
	}
}
